language: generic

sudo: required
services:
  - docker


before_install:
  - docker build -t johnpoff/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true johnpoff/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-753348154820"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
#

